Mmu wasa Changes
PSMRI/MMU-UI pull request #155
Opened 2024-11-29 13:33 UTC by NKOKKILIGADDA87

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [Y] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [Y] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [Y] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-11-29 14:41 UTC, sandipkarmakar3 reviewed
all changes I have reviewed. 
Everything is as per the requirement. 
we used sessionstorage.service to store the data to session storage.
we removed all localstorage code and used session storage.

2024-11-29 15:35 UTC, sandipkarmakar3 commented
@coderabbitai review

2024-11-30 08:04 UTC, sandipkarmakar3 commented
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-23 08:50 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-31 10:20 UTC, devikasuresh20 requested changes

2025-01-31 10:20 UTC, devikasuresh20 commented on src/environments/environment.ts
> +const ADMIN_API = `${adminIP}/adminapi-v3.0.0`;
@sandipkarmakar3  Please keep admin API version as "v1.0"

2025-01-31 10:20 UTC, devikasuresh20 commented on src/environments/environment.ts
> +const COMMON_API_OPEN = `${commonIP}commonapi-v3.0.0/`;
@sandipkarmakar3  Please keep common API version as "v1.0"

2025-01-31 10:20 UTC, devikasuresh20 commented on src/environments/environment.ts
> +const COMMON_API = `${commonIP}commonapi-v3.0.0/`;
@sandipkarmakar3  Please keep common API version as "v1.0"

2025-01-31 10:20 UTC, devikasuresh20 commented on src/environments/environment.ts
> +const MMU_API = `${mmuIP}mmuapi-v3.0.0/`;
@sandipkarmakar3  Please keep mmu API version as "v1.0"

2025-01-31 10:20 UTC, devikasuresh20 commented on src/environments/environment.ts
> +const FHIR_API = `${FHIRIP}/fhirapi-v3.0.0/`;
@sandipkarmakar3  Please keep "v1.0" for all APIs

2025-01-31 11:22 UTC, devikasuresh20 approved these changes

2025-01-31 11:22 UTC, merged